### ISSUE TITLE
morphology and ICD-0

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/oncoexporter#32]
The diagnosis table has entries such as - `8072/3` are ICD-O codes. 
For instance 8072/3 is  Nonkeratinizing squamous cell carcinoma.

Some but not all of these codes are available on NCIT.
For instance,

[Non-Keratinizing Large Cell Squamous Cell Carcinoma](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C65173?lang=en)

maps from NCIT:C65173.

Questions
- Is this thebest place to get ontology terms for ICD-O?
- Does NCIT team have a simple mapping file?
- Are there other resources such as MONDO?

**Comment by justaddcoffee** [comment]
closed by #56
