### ISSUE TITLE
Add stage to Disease object

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/oncoexporter#36]
This corresponds to the disease_stage field of GA4GH Disease, see here https://phenopacket-schema.readthedocs.io/en/latest/disease.html

We can use terms that descend from NCIT [Disease Stage Qualifier](https://ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C28108)

**Comment by justaddcoffee** [comment]
Addressed by https://github.com/monarch-initiative/oncoexporter/pull/53

**Comment by ielis** [comment]
Closing since the status indicates the issue has been resolved.
