### ISSUE TITLE
Minimum supported Python version

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/oncoexporter#59]
Hi @pnrobinson @justaddcoffee @msierk 

Can we relax the minimum supported Python version from `python >= 3.5` to `python >= 3.8`? 

According to [Status of Python versions](https://devguide.python.org/versions/) 3.5 has been end-of-life for >3 years and 3.8 is the last version that receives patches.

Using 3.8 or better will help me simplify loading of `Neoplasm_Core.csv` table in `cda_downloader` [here](https://github.com/monarch-initiative/oncoexporter/blob/c40b5eed60d8bbf67a006399715fb8d8d43d7428/src/oncoexporter/cda/cda_downloader.py#L6). The `importlib_resources` does not work for me from some reason and there is a [package](https://docs.python.org/3/library/importlib.resources.html) in stdlib Python since 3.7 that does the same thing.

**Comment by justaddcoffee** [comment]
+1 let's do this, 3.5 is old
