### ISSUE TITLE
Resolve issues with `CdaDiseaseFactory` tests

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/oncoexporter#66]
The tests of `CdaDiseaseFactory` are failing due to incomplete code of the `ICD-O` -> `NCIT` conversion.

@pnrobinson the code looks like a WIP from your side. Can you please implement the conversion? Alternatively, we need to discuss the requirements.

**Comment by pnrobinson** [comment]
I will not be able to work on this the next few days, this is a full week. However, Justin implemented download code for a mapping file and I think we might be close - I can cede this issue for now if you can work on it.

**Comment by ielis** [comment]
Sounds good, I think I and Justin can take it over.
