### ISSUE TITLE
Validate survival variables

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/oncoexporter#82]
Currently we take survival info from CDA.

This is what should be done. The method to calculate the survival time in days depends on the vital status (Alive/Deceased).

- Deceased
 - `Subject.days_to_death`: Number of days between the date used for index and the date from a person's date of death represented as a calculated number of days.
- Alive - we must calculate the difference between age at last encounter and diagnosis date
 - `Diagnosis.age_at_diagnosis`: The age in days of the individual at the time of diagnosis.
 - `Subject.days_to_birth`: Number of days between the date used for index and the date from a person's date of birth represented as a calculated negative number of days.

Alternatively, we can fetch the survival data directly from GDC, when we just fetch two columns:
- vital status (Alive/Deceased)
- survival in days - the number of days after making the diagnosis (index date?)

The [GDC API](https://docs.gdc.cancer.gov/API/Users_Guide/Data_Analysis/#survival-analysis-endpoint)

**Comment by justaddcoffee** [comment]
Alternatively, we could pull this survival time from GDC while we are pulling the mutation data, see here:

https://docs.gdc.cancer.gov/API/Users_Guide/Data_Analysis/#survival-analysis-endpoint

@sujaypatil96 how hard would it be to incorporate this into the code that does the call to GDC?

**Comment by justaddcoffee** [comment]
(h/t @msierk for finding that link in the docs)

**Comment by justaddcoffee** [comment]
@sujaypatil96 said he would have a try at pulling survival time from GDC

**Comment by sujaypatil96** [comment]
I'll spend some time looking into this next week. I'm OOO 4/4 and 4/5.

**Comment by sujaypatil96** [comment]
I have figured out how to pull in survival time (in days) information from GDC via the `/analysis/survival` endpoint. Now we just need to stick into the phenopacket on `VitalStatus`. Perhaps we can do this again on a mini hacking session @ielis @justaddcoffee?

**Comment by justaddcoffee** [comment]
great progress 

@sujaypatil96 @ielis what about a hacking session Fri 2 pm Eastern US time on my zoom?

**Comment by sujaypatil96** [comment]
I won't be able to make the hacking session on friday because I'll be at an all day training session on thursday, 4/11 and friday 4/12 this week.

But as far as the task goes I think I've completed pulling in survival times and vital status information from GDC and plugged them into the phenopackets as well. It would be nice if you could test it once and let me know.

**Comment by sujaypatil96** [comment]
Notes from discussion with @justaddcoffee on 4/16.

If person/patient is "Alive" then we need a way of populating survival time in days, and we can do that as follows:

```
when we last saw the patient (day of last encounter) - when the patient was diagnosed
```
